# Generated by Django 4.2.4 on 2023-08-29 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadeira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('horas', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('ano', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Configuracoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semestre_ativo', models.IntegerField(choices=[(1, '1º Semestre'), (2, '2º Semestre')])),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('celular', models.PositiveIntegerField()),
                ('nascimento', models.DateField()),
                ('bi', models.CharField(max_length=13)),
                ('ano_ingresso', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('codigo_estudante', models.CharField(max_length=20, unique=True)),
                ('senha_inicial', models.CharField(max_length=128)),
                ('periodo', models.CharField(choices=[('D', 'Diurno'), ('N', 'Noturno')], max_length=1)),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curso')),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('apelido', models.CharField(max_length=50)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1)),
                ('celular', models.IntegerField()),
                ('nascimento', models.DateField()),
                ('bi_codigo', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inscricao', models.DateTimeField(auto_now_add=True)),
                ('cadeira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.cadeira')),
                ('estudante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.estudante')),
            ],
        ),
        migrations.AddField(
            model_name='cadeira',
            name='curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
        ),
    ]
