# Generated by Django 4.2.4 on 2023-08-29 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_estudante_is_active_estudante_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='estudante',
            name='is_staff',
        ),
    ]
