# Generated by Django 4.2.4 on 2023-08-31 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_estudante_is_active_remove_estudante_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudante',
            name='senha_inicial',
        ),
    ]
