# Generated by Django 4.2.4 on 2023-09-01 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_estudante_senha_inicial'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracoes',
            name='periodo_inscricao_aberto',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='cadeira_feita',
            field=models.BooleanField(default=False),
        ),
    ]
