# Generated by Django 4.2.4 on 2023-09-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_cadeiraconcluida'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadeiraconcluida',
            name='cadeira',
        ),
        migrations.AddField(
            model_name='cadeiraconcluida',
            name='cadeiras',
            field=models.ManyToManyField(to='main.cadeira'),
        ),
    ]
