# Generated by Django 4.2.4 on 2023-09-01 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_remove_cadeiraconcluida_cadeira_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadeiraconcluida',
            name='curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.curso'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cadeiraconcluida',
            name='cadeiras',
            field=models.ManyToManyField(limit_choices_to={'curso': models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.curso')}, to='main.cadeira'),
        ),
        migrations.AlterField(
            model_name='cadeiraconcluida',
            name='estudante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
