# Generated by Django 4.2.4 on 2023-09-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_cadeiraconcluida_curso_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CadeiraConcluida',
        ),
    ]
