# Generated by Django 4.2.4 on 2023-09-07 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_inscricao_feito'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inscricao',
        ),
    ]
