# Generated by Django 4.2.4 on 2023-09-07 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_inscricao'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Funcionario',
        ),
    ]
