# Generated by Django 4.2.4 on 2023-11-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_delete_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='codigo_estudante',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
